"""JARVIS contracts — the source of truth for all typed interfaces."""

from jarvis.contracts.errors import (
    AccessError,
    ErrorCode,
    EvidenceError,
    GovernorError,
    IndexingError,
    JarvisError,
    RetrievalError,
    RuntimeError_,
    StorageError,
    ToolError,
)
from jarvis.contracts.models import (
    AnswerDraft,
    AssembledContext,
    ChunkRecord,
    CitationRecord,
    ConversationTurn,
    DocumentElement,
    DocumentRecord,
    DraftExportRequest,
    DraftExportResult,
    EvidenceItem,
    ExtractedFact,
    HybridSearchResult,
    ParsedDocument,
    RuntimeDecision,
    SearchHit,
    SystemStateSnapshot,
    TaskLogEntry,
    TypedQueryFragment,
    VectorHit,
    VerifiedEvidenceSet,
)
from jarvis.contracts.protocols import (
    ApprovalGatewayProtocol,
    ContextAssemblerProtocol,
    ConversationStoreProtocol,
    EmbeddingRuntimeProtocol,
    EvidenceBuilderProtocol,
    FTSRetrieverProtocol,
    GovernorProtocol,
    HybridFusionProtocol,
    LLMBackendProtocol,
    LLMGeneratorProtocol,
    QueryDecomposerProtocol,
    TaskLogStoreProtocol,
    ToolRegistryProtocol,
    VectorRetrieverProtocol,
)
from jarvis.contracts.states import (
    AccessStatus,
    CitationState,
    GovernorMode,
    IndexingStatus,
    RuntimeTier,
    TaskStatus,
    ThermalState,
    ToolName,
)

__all__ = [
    # Models
    "TypedQueryFragment",
    "SearchHit",
    "VectorHit",
    "HybridSearchResult",
    "CitationRecord",
    "EvidenceItem",
    "VerifiedEvidenceSet",
    "ExtractedFact",
    "AssembledContext",
    "AnswerDraft",
    "DraftExportRequest",
    "DraftExportResult",
    "ConversationTurn",
    "TaskLogEntry",
    "DocumentRecord",
    "ChunkRecord",
    "DocumentElement",
    "ParsedDocument",
    "RuntimeDecision",
    "SystemStateSnapshot",
    # States
    "CitationState",
    "TaskStatus",
    "GovernorMode",
    "ToolName",
    "IndexingStatus",
    "AccessStatus",
    "RuntimeTier",
    "ThermalState",
    # Errors
    "ErrorCode",
    "JarvisError",
    "RetrievalError",
    "EvidenceError",
    "RuntimeError_",
    "IndexingError",
    "ToolError",
    "AccessError",
    "GovernorError",
    "StorageError",
    # Protocols
    "QueryDecomposerProtocol",
    "FTSRetrieverProtocol",
    "VectorRetrieverProtocol",
    "HybridFusionProtocol",
    "EvidenceBuilderProtocol",
    "ContextAssemblerProtocol",
    "LLMBackendProtocol",
    "LLMGeneratorProtocol",
    "EmbeddingRuntimeProtocol",
    "GovernorProtocol",
    "ConversationStoreProtocol",
    "TaskLogStoreProtocol",
    "ToolRegistryProtocol",
    "ApprovalGatewayProtocol",
]
